# Simple workflow for deploying static content to GitHub Pages
name: Deploy storybook component site to Github pages

on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Manual Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm install # default: npm ci
          build_command: npm run build-storybook # default: npm run build-storybook
          path: storybook-static # change to your build folder
          checkout: false
